master
Greenstand/treetracker-android pull request #637
Opened 2021-06-10 08:59 UTC by EngrTaofeek

Increased the width of the button so as to display the language text in the button completely.

2021-06-10 17:29 UTC, Elforama requested changes
Thanks for the PR!

Can you please update the language button to use the DepthButton? It doesn't need to rely on TextButton anymore. All buttons will move towards depthbutton

2021-06-10 17:41 UTC, Elforama commented on build.gradle
> +        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.5.2'
We don't need to change gradle. If this is required to build it locally, just don't check it into git.

2021-06-11 00:03 UTC, EngrTaofeek commented
I forgot to uncheck the gradle file while I made the commit. I would switch the language button to DepthButtons and make a pull request

2021-06-17 14:25 UTC, Elforama commented
Hey @EngrTaofeek, it looks like you need to rebase this branch to fix the merge conflicts.

2022-02-05 14:35 UTC, closed without merging