Dashboard Upload Bar
Greenstand/treetracker-android pull request #646
Opened 2021-08-23 16:43 UTC by MarcellinoCO

Implemented upload progress bar in the Dashboard screen. I have a question tho, will the bar be full or empty if there are no trees to be uploaded? Currently, it will be empty.

Current screenshot:
![image](https://user-images.githubusercontent.com/19645892/130484748-a600ab64-9c9b-48f4-acab-6749417f4cf9.png)

2021-08-24 19:13 UTC, Elforama commented
The bar will be full once everything is uploaded. Correct @ZavenArra?

Otherwise this is looking great!

2021-08-24 19:15 UTC, Elforama requested changes
Please update the progress bar filled state.

2021-08-25 02:32 UTC, MarcellinoCO commented
Thank you, Jonathan! 😁

The current calculation for the progress bar is `treesSynced / totalTrees`. I hope this is correct because I haven't been able to add a tree and test it directly.

Current screenshot:
![image](https://user-images.githubusercontent.com/19645892/130716871-fe386109-3e8b-4bc8-92ef-33b42cfa97d3.png)

2021-08-25 03:12 UTC, Elforama commented
Looks great, thx!

2021-08-25 03:12 UTC, Elforama approved these changes

2021-08-29 21:15 UTC, merged