Update user image
Greenstand/treetracker-android pull request #763
Opened 2022-01-26 14:07 UTC by EngrTaofeek

fixes #724 Updated user Image to depth button and fixed a tiny bug in the TreeCaptureScreen.kt
![WhatsApp Image 2022-01-26 at 15 05 37-2](https://user-images.githubusercontent.com/38661872/151177733-6e5e116a-4de5-49e8-8d5c-881bec19c447.jpeg)
![WhatsApp Image 2022-01-26 at 15 05 37](https://user-images.githubusercontent.com/38661872/151177743-4a039930-c788-4295-a0f8-1331cf788757.jpeg)

2022-01-26 17:46 UTC, Elforama requested changes
Looks good, just a minor fix.

2022-01-26 17:46 UTC, Elforama commented on app/src/main/java/org/greenstand/android/TreeTracker/view/TextButton.kt
> +fun userImageButton(
Please use a capitol letter at the start. UserImageButton

2022-02-04 03:17 UTC, Elforama commented
@EngrTaofeek Please resolve any conflicts and I get merge it.

2022-02-04 17:08 UTC, EngrTaofeek commented
@Elforama conflicts fixed and branch rebased to master.

2022-02-04 17:13 UTC, merged