Feat - View Live Web Map!
Greenstand/treetracker-android pull request #766
Opened 2022-01-31 06:23 UTC by sidsharma2002

2022-01-31 15:29 UTC, Elforama requested changes
Looks great! I just added some minor comments to address if you can.

2022-01-31 15:29 UTC, Elforama commented on app/src/main/java/org/greenstand/android/TreeTracker/signup/CredentialEntryView.kt
> +    val navigateToWebPage: () -> Unit = {
Can we move this function inline where it's called?

2022-01-31 15:39 UTC, sidsharma2002 commented on app/src/main/java/org/greenstand/android/TreeTracker/signup/SignupViewModel.kt
> +    fun updateStateAccToUserExistence() {
ok, but earlier it was doesUserExists() which was totally out of context I think

2022-01-31 15:41 UTC, sidsharma2002 commented on app/src/main/java/org/greenstand/android/TreeTracker/signup/SignupViewModel.kt
> +    fun isInternetAvailable() : Boolean{
got it

2022-01-31 20:47 UTC, EngrTaofeek commented on app/src/main/java/org/greenstand/android/TreeTracker/signup/SignupViewModel.kt
> +    fun updateStateAccToUserExistence() {
I quite agree with @Elforama  view. Check out the interesting answers here about some naming conventions https://stackoverflow.com/questions/3874350/naming-conventions-for-java-methods-that-return-boolean

2022-02-01 19:27 UTC, Elforama commented on app/src/main/java/org/greenstand/android/TreeTracker/signup/SignupViewModel.kt
> +    fun updateStateAccToUserExistence() {
To simplify it, we can name is 'submitInfo()' or something of that sort. From the views point of view, that's what is happening.

2022-02-04 01:35 UTC, Elforama requested changes
Thanks for making the fixes. I've tested it out and it works well! I've added a few more comments, once they are addressed this should be good to merge.

2022-02-04 01:35 UTC, Elforama commented on app/src/main/java/org/greenstand/android/TreeTracker/signup/SignupViewModel.kt
> +    val isInternetAvailable: LiveData<Boolean> = _isInternetAvailable
This is my mistake, I should I mentioned this earlier.

For the each screen, we're trying to keep it simple by having them all rely on a single 'state' object called "state". In this case we can put the 'isInternetAvailable' as a field inside the SignupState object. This object is passed to the screen already, so you'd access it like 'state.isInternetAvailble'.

To see how the state object is updated, you can see the 'updateName' method.

2022-02-04 01:35 UTC, Elforama commented on app/src/main/java/org/greenstand/android/TreeTracker/view/TextButton.kt
> +@Composable
Please rebase to remove changes that have been merged already.

2022-02-04 01:35 UTC, Elforama commented on app/src/main/java/org/greenstand/android/TreeTracker/utilities/Constants.kt
> +    const val TREE_TRACKER_URL = "http://www.treetracker.org"
This link doesn't seem to work for me. You can use "https://map.treetracker.org/"

2022-02-05 14:32 UTC, merged