Fix  : No snackbar when sync button is clicked for the first time
Greenstand/treetracker-android pull request #940
Opened 2022-03-18 13:05 UTC by sidsharma2002

#888 Initially the flow was wrong because the starting value of _isSyncing is null. When we open the next time,   unexpectedly the worker emits a work with succeeded state , the null check in the when block prevents the snackbar to show but sets its value as false. Then, when we click the sync button everything happens as intended (due to the false value set).

2022-03-18 13:36 UTC, Elforama requested changes
Great work, it looks like the issue is resolved.

There is just one issue. When capturing trees before the user syncs, the dashboard doesn't show the tree count. Adding back the updateData method seems to fix it.

2022-03-18 13:36 UTC, Elforama commented on app/src/main/java/org/greenstand/android/TreeTracker/dashboard/DashboardViewModel.kt
> -        updateData()
This method was here to refresh the screen when going back to it after capturing trees. We still need it.

2022-03-18 20:31 UTC, Elforama approved these changes
Awesome job, it works well!

Please fix any conflicts and I'll get this merged.

2022-03-19 00:12 UTC, ZavenArra approved these changes
Tested and works well.

2022-03-19 00:12 UTC, merged